version: '2'
services:
  mongo:
    container_name: uds2-mongodb
    image: mongo
    command: mongod --smallfiles --oplogSize 128
    labels:
      traefik.enable: "false"
  rocketchat:
    #container_name: uds2-rocketchat
    image: rocketchat/rocket.chat:latest
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://uds2-mongodb:27017/rocketchat
    links:
      - mongo:uds2-mongodb
    #ports:
    #  - "3000:3000"
    labels:
      traefik.backend: "rocketchat"
  hubot:
    container_name: usds2-hubot
    image: rocketchat/hubot-rocketchat
    environment:
      - ROCKETCHAT_URL=uds2-rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    ports:
      - 3001:3001
    labels:
      traefik.enable: "false"
  traefik:
    container_name: uds2-traefik
    image: containous/traefik
    volumes:
      - $PWD/traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
